import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import replitAuthRouter from "./replit-auth";
import usersRouter from "./users";
import referenceRouter from "./reference";
import vehiclesRouter from "./vehicles";
import sellerRouter from "./seller";
import favoritesRouter from "./favorites";
import chatRouter from "./chat";
import notificationsRouter from "./notifications";
import buyerRouter from "./buyer";
import quotationsRouter from "./quotations";
import ordersRouter from "./orders";
import paymentsRouter from "./payments";
import storageRouter from "./storage";
import freightRouter from "./freight";
import freightChatRouter from "./freight-chat";
import shipmentsRouter from "./shipments";
import adminRouter from "./admin";
import savedSearchesRouter from "./saved-searches";
import adminMessagesRouter from "./admin-messages";
import mailboxesRouter from "./mailboxes";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(replitAuthRouter);
router.use(usersRouter);
router.use(referenceRouter);
router.use(vehiclesRouter);
router.use(sellerRouter);
router.use(favoritesRouter);
router.use(chatRouter);
router.use(notificationsRouter);
router.use(buyerRouter);
router.use(quotationsRouter);
router.use(ordersRouter);
router.use(paymentsRouter);
router.use(storageRouter);
router.use(freightRouter);
router.use(freightChatRouter);
router.use(shipmentsRouter);
router.use(adminRouter);
router.use(adminMessagesRouter);
router.use(mailboxesRouter);
router.use(savedSearchesRouter);

export default router;
