// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-variants/ElectricPrecision.tsx": () => import("../components/mockups/login-variants/ElectricPrecision.tsx"),
  "./components/mockups/login-variants/StarkEditorial.tsx": () => import("../components/mockups/login-variants/StarkEditorial.tsx"),
  "./components/mockups/login-variants/WarmPremium.tsx": () => import("../components/mockups/login-variants/WarmPremium.tsx")
};
